import:
  #Catppuccin Moca Theme
  - ~/.config/alacritty/catppuccin-mocha.yml

window:
  opacity: 0.8
  dimensions:
    columns: 80
    lines: 22
  padding:
    x: 5
    y: 2

scrolling:
  history: 2000

mouse:
  hide_when_typing: true

font:
  size: 11
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular
  bold:
   family: "JetBrainsMono Nerd Font"
   style: Bold
  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic
  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: Bold Italic

env:
  TERM: xterm-256color

# Auto-start tmux
shell:
  program: fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"
